{{- if (.Values.builder).enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ir-engine.builder.fullname" . }}
  labels:
    {{- include "ir-engine.builder.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - endpoints
      - deployments
      - secrets
      - serviceaccounts
      - configmaps
      - clusterroles
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - "agones.dev"
    resources:
      - fleets
      - fleet
      - fleets.agones.dev
      - gameservers
      - gameserver
      - gameservers.agones.dev
      - gameserversets
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - "autoscaling.agones.dev"
    resources:
      - "fleetautoscalers"
    verbs:
      - get
      - patch
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
  - apiGroups:
      - "batch"
    resources:
      - "cronjobs"
    verbs:
      - get
      - patch
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "ingresses"
    verbs:
      - "get"
{{- end }}
