{{- if and (.Values.builder).enabled ((.Values.builder).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ir-engine.builder.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ir-engine.builder.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.builder.extraEnv.DESTINATION_REPO_PROVIDER "gcp" }}
    iam.gke.io/gcp-service-account: gke-builder-sa@{{ .Release.Namespace }}.iam.gserviceaccount.com
    {{- end }}
    {{- with .Values.builder.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}
