{{- if (.Values.builder).enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ir-engine.builder.fullname" . }}
  labels:
    {{- include "ir-engine.builder.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: k8s-mysql-ksa
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ir-engine.builder.fullname" . }}
{{- end -}}
