{{- if and ((.Values.builder).kaniko).enabled (.Values.client).enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ir-engine.builder.kaniko.fullname" . }}-client
  labels:
    {{- include "ir-engine.builder.kaniko.labels" . | nindent 4 }}
spec:
  manualSelector: true
  backoffLimit: 0
  selector:
    matchLabels:
      {{- include "ir-engine.builder.kaniko.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ir-engine.builder.kaniko.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/kaniko-configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.builder.kaniko.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ir-engine.builder.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.builder.kaniko.podSecurityContext | nindent 8 }}
      {{- $releaseName := .Release.Name }}
      {{ if not (empty .Values.release) }}
      {{- $releaseName = .Values.release.name | default .Release.Name }}
      {{ end }}
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-client
          securityContext:
            {{- toYaml .Values.builder.kaniko.securityContext | nindent 12 }}
          image: "bitnami/kaniko:{{ .Values.builder.kaniko.image.tag }}"
          imagePullPolicy: IfNotPresent
          args: [
            "--cache=true",
            "--cache-run-layers=true",
            "--cache-copy-layers=true",
            {{ if eq .Values.builder.extraEnv.SERVE_CLIENT_FROM_STORAGE_PROVIDER "true" }}
            "--dockerfile=./dockerfiles/client/Dockerfile-client-serve-static",
            {{ else }}
            "--dockerfile=./dockerfiles/client/Dockerfile-client",
            {{- end }}
            "--context={{ .Values.builder.extraEnv.KANIKO_CONTEXT_PROTOCOL }}://{{ .Values.builder.extraEnv.KANIKO_CONTEXT_REPO }}/builder-context-{{ .Values.builder.extraEnv.START_TIME }}.tar.gz",
            "--no-push=true",
            "--cache-repo={{ .Values.builder.extraEnv.DESTINATION_REPO_URL }}/{{ .Values.builder.extraEnv.DESTINATION_REPO_NAME_CLIENT }}",
            "--build-arg=REPO_URL={{ .Values.builder.extraEnv.SOURCE_REPO_URL }}",
            "--build-arg=REPO_NAME={{ .Values.builder.extraEnv.SOURCE_REPO_NAME_API }}",
            "--build-arg=STAGE={{ .Values.builder.extraEnv.STAGE }}",
            "--build-arg=KUBERNETES={{ .Values.builder.extraEnv.KUBERNETES }}",
            "--build-arg=TAG={{ .Values.builder.extraEnv.TAG }}",
            "--build-arg=NODE_ENV={{ .Values.builder.extraEnv.NODE_ENV }}",
            "--build-arg=STORAGE_PROVIDER={{ .Values.builder.extraEnv.STORAGE_PROVIDER }}",
            "--build-arg=STORAGE_CDN_DOMAIN={{ .Values.builder.extraEnv.STORAGE_CDN_DOMAIN }}",
            "--build-arg=STORAGE_CLOUDFRONT_DISTRIBUTION_ID={{ .Values.builder.extraEnv.STORAGE_CLOUDFRONT_DISTRIBUTION_ID }}",
            "--build-arg=STORAGE_STATIC_RESOURCE_BUCKET={{ .Values.builder.extraEnv.STORAGE_STATIC_RESOURCE_BUCKET }}",
            "--build-arg=STORAGE_AWS_ACCESS_KEY_ID={{ .Values.builder.extraEnv.STORAGE_AWS_ACCESS_KEY_ID }}",
            "--build-arg=STORAGE_AWS_ACCESS_KEY_SECRET={{ .Values.builder.extraEnv.STORAGE_AWS_ACCESS_KEY_SECRET }}",
            "--build-arg=STORAGE_AWS_ROLE_ARN={{ .Values.builder.extraEnv.STORAGE_AWS_ROLE_ARN }}",
            "--build-arg=STORAGE_AWS_ENABLE_ACLS={{ .Values.builder.extraEnv.STORAGE_AWS_ENABLE_ACLS }}",
            "--build-arg=STORAGE_GCP_ACCESS_KEY_ID={{ .Values.builder.extraEnv.STORAGE_GCP_ACCESS_KEY_ID }}",
            "--build-arg=STORAGE_GCP_ACCESS_KEY_SECRET={{ .Values.builder.extraEnv.STORAGE_GCP_ACCESS_KEY_SECRET }}",
            "--build-arg=STORAGE_GCP_ROLE_ARN={{ .Values.builder.extraEnv.STORAGE_GCP_ROLE_ARN }}",
            "--build-arg=STORAGE_REGION={{ .Values.builder.extraEnv.STORAGE_REGION }}",
            "--build-arg=STORAGE_S3_AVATAR_DIRECTORY={{ .Values.builder.extraEnv.STORAGE_S3_AVATAR_DIRECTORY }}",
            "--build-arg=SERVE_CLIENT_FROM_STORAGE_PROVIDER={{ .Values.builder.extraEnv.SERVE_CLIENT_FROM_STORAGE_PROVIDER }}",
            "--build-arg=MYSQL_HOST={{ .Values.sql.host }}",
            "--build-arg=MYSQL_USER={{ .Values.sql.user }}",
            "--build-arg=MYSQL_PORT={{ .Values.sql.port }}",
            "--build-arg=MYSQL_PASSWORD={{ .Values.sql.password }}",
            "--build-arg=MYSQL_DATABASE={{ .Values.sql.database }}",
            "--build-arg=GCP_EDGE_CACHE_SERVICE={{ .Values.builder.extraEnv.GCP_EDGE_CACHE_SERVICE }}",
            "--build-arg=GCP_PROJECT={{ .Values.builder.extraEnv.GCP_PROJECT }}",
            "--build-arg=GCP_URL_MAP={{ .Values.builder.extraEnv.GCP_URL_MAP }}",
            "--build-arg=APP_HOST={{ .Values.builder.extraEnv.APP_HOST }}",
            "--build-arg=GCP_PROJECT={{ .Values.builder.extraEnv.GCP_PROJECT }}",
            "--build-arg=GCP_EDGE_CACHE_SERVICE={{ .Values.builder.extraEnv.GCP_EDGE_CACHE_SERVICE }}",
            "--build-arg=GCP_URL_MAP={{ .Values.builder.extraEnv.GCP_URL_MAP }}",
            "--build-arg=VITE_APP_HOST={{ .Values.builder.extraEnv.VITE_APP_HOST }}",
            "--build-arg=VITE_APP_PORT={{ .Values.builder.extraEnv.VITE_APP_PORT }}",
            "--build-arg=VITE_PWA_ENABLED={{ .Values.builder.extraEnv.VITE_PWA_ENABLED }}",
            "--build-arg=VITE_SERVER_HOST={{ .Values.builder.extraEnv.VITE_SERVER_HOST }}",
            "--build-arg=VITE_SERVER_PORT={{ .Values.builder.extraEnv.VITE_SERVER_PORT }}",
            "--build-arg=VITE_FEATHERS_STORE_KEY={{ .Values.builder.extraEnv.VITE_FEATHERS_STORE_KEY }}",
            "--build-arg=VITE_FILE_SERVER={{ .Values.builder.extraEnv.VITE_FILE_SERVER }}",
            "--build-arg=VITE_MEDIATOR_SERVER={{ .Values.builder.extraEnv.VITE_MEDIATOR_SERVER }}",
            "--build-arg=VITE_8TH_WALL={{ .Values.builder.extraEnv.VITE_8TH_WALL }}",
            "--build-arg=VITE_INSTANCESERVER_HOST={{ .Values.builder.extraEnv.VITE_INSTANCESERVER_HOST }}",
            "--build-arg=VITE_INSTANCESERVER_PORT={{ .Values.builder.extraEnv.VITE_INSTANCESERVER_PORT }}",
            "--build-arg=VITE_LOCAL_BUILD={{ .Values.builder.extraEnv.VITE_LOCAL_BUILD }}",
            "--build-arg=VITE_SOURCEMAPS={{ .Values.builder.extraEnv.VITE_SOURCEMAPS }}",
            "--build-arg=VITE_READY_PLAYER_ME_URL={{ .Values.builder.extraEnv.VITE_READY_PLAYER_ME_URL }}",
            "--build-arg=VITE_TERMS_OF_SERVICE_ADDRESS={{ .Values.builder.extraEnv.VITE_TERMS_OF_SERVICE_ADDRESS }}",
            "--build-arg=VITE_DISABLE_LOG={{ .Values.builder.extraEnv.VITE_DISABLE_LOG }}",
            "--build-arg=VITE_AVATURN_URL={{ .Values.builder.extraEnv.VITE_AVATURN_URL }}",
            "--build-arg=VITE_AVATURN_API={{ .Values.builder.extraEnv.VITE_AVATURN_API }}",
            "--build-arg=VITE_ZENDESK_ENABLED={{ .Values.builder.extraEnv.VITE_ZENDESK_ENABLED }}",
            "--build-arg=VITE_ZENDESK_KEY={{ .Values.builder.extraEnv.VITE_ZENDESK_KEY }}",
            "--build-arg=VITE_DNS_PROVIDER={{ .Values.builder.extraEnv.VITE_DNS_PROVIDER }}",
            "--build-arg=VITE_ZENDESK_AUTHENTICATION_ENABLED={{ .Values.builder.extraEnv.VITE_ZENDESK_AUTHENTICATION_ENABLED }}"
          ]
          envFrom:
            - configMapRef:
                name: {{ include "ir-engine.builder.kaniko.fullname" . }}
                optional: true
          env:
            - name: RELEASE_NAME
              value: {{ $releaseName }}
            - name: SERVICE
              value: client
            - name: BUILDER_REPOSITORY
              value: {{ .Values.builder.image.repository }}
            # GOOGLE_PROJECT_ID will be an empty string if deployed on AWS
            - name: GOOGLE_PROJECT_ID
              value: {{ .Values.googleProjectID }}
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
          volumeMounts:
            - name: client-kaniko-storage
              mountPath: /tmp

      {{- if eq .Values.cloudProvider "gcp" }}
      initContainers:
        - name: cloud-sql-proxy
          restartPolicy: Always
          # It is recommended to use the latest version of the Cloud SQL Auth Proxy
          # Make sure to update on a regular schedule!
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.1
          args:
            # If connecting from a VPC-native GKE cluster, you can use the
            # following flag to have the proxy connect over private IP
            - "--private-ip"

            # Enable structured logging with LogEntry format:
            - "--structured-logs"
            - "--auto-iam-authn"

            # Replace DB_PORT with the port the proxy should listen on
            - "--port=3306"
            - "{{ .Values.googleProjectID }}:us-central1:{{ .Release.Namespace }}-mysql"

          securityContext:
            # The default Cloud SQL Auth Proxy image runs as the
            # "nonroot" user and group (uid: 65532) by default.
            runAsNonRoot: true
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
      {{- end }}
      volumes:
        - name: client-kaniko-storage
      {{- with .Values.builder.kaniko.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.builder.kaniko.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.builder.kaniko.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
