{{- if and ((.Values.builder).kaniko).enabled (.Values.instanceserver).enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ir-engine.builder.kaniko.fullname" . }}-instanceserver
  labels:
    {{- include "ir-engine.builder.kaniko.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ir-engine.kaniko.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ir-engine.builder.kaniko.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/kaniko-configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.builder.kaniko.imagePullSecrets }}
    imagePullSecrets:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    serviceAccountName: {{ include "ir-engine.builder.kaniko.serviceAccountName" . }}
    securityContext:
      {{- toYaml .Values.builder.kaniko.podSecurityContext | nindent 8 }}
    {{- $releaseName := .Release.Name }}
    {{ if not (empty .Values.release) }}
    {{- $releaseName = .Values.release.name | default .Release.Name }}
    {{ end }}
    containers:
      - name: {{ .Chart.Name }}-instanceserver
        securityContext:
          {{- toYaml .Values.builder.kaniko.securityContext | nindent 12 }}
        image: "bitnami/kaniko:{{ .Values.builder.kaniko.image.tag }}"
        imagePullPolicy: IfNotPresent
        args: [
          "--cache=true",
          "--cache-run-layer=true",
          "--cache-copy-layers=true",
          "--dockerfile=/app/dockerfiles/instanceserver/Dockerfile-instanceserver",
          "--context=${{ .Values.builder.kaniko.bucket }}/${{ .Values.builder.kaniko.instanceserver.contextPath }}",
          "--destination=${{ .Values.builder.extraEnv.DESTINATION_REPO_URL }}/${{ .Values.builder.extraEnv.DESTINATION_REPO_NAME }}"
        ]
        envFrom:
          - configMapRef:
              name: {{ include "ir-engine.builder.kaniko.fullname" . }}
              optional: true
        env:
          - name: RELEASE_NAME
            value: {{ $releaseName }}
          - name: SERVICE
            value: instanceserer
          - name: BUILDER_REPOSITORY
            value: {{ .Values.builder.image.repository }}
          # GOOGLE_PROJECT_ID will be an empty string if deployed on AWS
          - name: GOOGLE_PROJECT_ID
            value: {{ .Values.googleProjectID }}
          - name: NAMESPACE
            value: {{ .Release.Namespace }}
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker
          - name: dockerfile-storage
            mountPath: /workspace
        volumes:
          - name: kaniko-secret
            secret:
              secretName: regcred
              items:
                - key: .dockerconfigjson
                  path: config.json
          - name: dockerfile-storage
            persistentVolumeClaim:
              claimName: dockerfile-claim
    {{- with .Values.builder.kaniko.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.builder.kaniko.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.builder.kaniko.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end }}
