{{- if and ((.Values.builder).kaniko).enabled (.Values.instanceserver).enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ir-engine.builder.kaniko.fullname" . }}-instanceserver
  labels:
    {{- include "ir-engine.builder.kaniko.labels" . | nindent 4 }}
spec:
  manualSelector: true
  backoffLimit: 1
  selector:
    matchLabels:
      {{- include "ir-engine.builder.kaniko.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ir-engine.builder.kaniko.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/kaniko-configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.builder.kaniko.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ir-engine.builder.kaniko.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.builder.kaniko.podSecurityContext | nindent 8 }}
      {{- $releaseName := .Release.Name }}
      {{ if not (empty .Values.release) }}
      {{- $releaseName = .Values.release.name | default .Release.Name }}
      {{ end }}
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-instanceserver
          securityContext:
            {{- toYaml .Values.builder.kaniko.securityContext | nindent 12 }}
          image: "bitnami/kaniko:{{ .Values.builder.kaniko.image.tag }}"
          imagePullPolicy: IfNotPresent
          args: [
            "--cache=true",
            "--cache-run-layers=true",
            "--cache-copy-layers=true",
            "--dockerfile=/app/dockerfiles/instanceserver/Dockerfile-instanceserver",
            "--context={{ .Values.builder.kaniko.context_repo }}/builder-context-{{ .Values.builder.extraEnv.START_TIME }}.tar.gz",
            "--destination={{ .Values.builder.extraEnv.DESTINATION_REPO_URL_INSTANCESERVER }}/{{ .Values.builder.extraEnv.DESTINATION_REPO_NAME_INSTANCESERVER }}:{{ .Values.builder.extraEnv.TAG }}_{{ .Values.builder.extraEnv.START_TIME }}",
            "--destination={{ .Values.builder.extraEnv.DESTINATION_REPO_URL_INSTANCESERVER }}/{{ .Values.builder.extraEnv.DESTINATION_REPO_NAME_INSTANCESERVER }}:latest_instanceserver"
          ]
          envFrom:
            - configMapRef:
                name: {{ include "ir-engine.builder.kaniko.fullname" . }}
                optional: true
          env:
            - name: RELEASE_NAME
              value: {{ $releaseName }}
            - name: SERVICE
              value: instanceserer
            - name: BUILDER_REPOSITORY
              value: {{ .Values.builder.image.repository }}
            # GOOGLE_PROJECT_ID will be an empty string if deployed on AWS
            - name: GOOGLE_PROJECT_ID
              value: {{ .Values.googleProjectID }}
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
          volumeMounts:
            - name: dockerfile-storage
              mountPath: /app
      volumes:
        - name: dockerfile-storage
      {{- with .Values.builder.kaniko.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.builder.kaniko.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.builder.kaniko.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
