{{- if ((.Values.builder).kaniko).enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ir-engine.builder.kaniko.fullname" . }}
  labels:
    {{- include "ir-engine.builder.kaniko.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.builder.kaniko.replicaCount }}
  selector:
    matchLabels:
      {{- include "ir-engine.kaniki.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ir-engine.builder.kaniko.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/api-server-configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.builder.kaniko.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "ir-engine.builder.kaniko.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.builder.kaniko.podSecurityContext | nindent 8 }}
      {{- $releaseName := .Release.Name }}
      {{ if not (empty .Values.release) }}
      {{- $releaseName = .Values.release.name | default .Release.Name }}
      {{ end }}
      containers:
        {{- if (.Values.api).enabled -}}
        - name: {{ .Chart.Name }}-api
          securityContext:
            {{- toYaml .Values.builder.kaniko.securityContext | nindent 12 }}
          image: "bitnami/kaniko:{{ .Values.builder.kaniko.image.tag }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ include "ir-engine.builder.kaniko.fullname" . }}
                optional: true
          env:
            - name: RELEASE_NAME
              value: {{ $releaseName }}
            - name: SERVICE
              value: api
            - name: BUILDER_REPOSITORY
              value: {{ .Values.builder.image.repository }}            
            # GOOGLE_PROJECT_ID will be an empty string if deployed on AWS 
            - name: GOOGLE_PROJECT_ID
              value: {{ .Values.googleProjectID }}         
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
        {{- end }}
        {{- if (.Values.instanceserver).enabled -}}
          - name: {{ .Chart.Name }}-instanceserver
            securityContext:
              {{- toYaml .Values.builder.kaniko.securityContext | nindent 12 }}
            image: "bitnami/kaniko:{{ .Values.builder.kaniko.image.tag }}"
            imagePullPolicy: IfNotPresent
            envFrom:
              - configMapRef:
                  name: {{ include "ir-engine.builder.kaniko.fullname" . }}
                  optional: true
            env:
              - name: RELEASE_NAME
                value: {{ $releaseName }}
              - name: SERVICE
                value: instanceserver
              - name: BUILDER_REPOSITORY
                value: {{ .Values.builder.image.repository }}
              # GOOGLE_PROJECT_ID will be an empty string if deployed on AWS
              - name: GOOGLE_PROJECT_ID
                value: {{ .Values.googleProjectID }}
              - name: NAMESPACE
                value: {{ .Release.Namespace }}
        {{- end }}

        {{- if (.Values.client).enabled -}}
          - name: {{ .Chart.Name }}-client
            securityContext:
              {{- toYaml .Values.builder.kaniko.securityContext | nindent 12 }}
            image: "bitnami/kaniko:{{ .Values.builder.kaniko.image.tag }}"
            imagePullPolicy: IfNotPresent
            envFrom:
              - configMapRef:
                  name: {{ include "ir-engine.builder.kaniko.fullname" . }}
                  optional: true
            env:
              - name: RELEASE_NAME
                value: {{ $releaseName }}
              - name: SERVICE
                value: client
              - name: BUILDER_REPOSITORY
                value: {{ .Values.builder.image.repository }}
              # GOOGLE_PROJECT_ID will be an empty string if deployed on AWS
              - name: GOOGLE_PROJECT_ID
                value: {{ .Values.googleProjectID }}
              - name: NAMESPACE
                value: {{ .Release.Namespace }}
        {{- end }}
      {{- with .Values.builder.kaniko.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.builder.kaniko.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.builder.kaniko.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
