{{- if and (.Values.api).enabled ((.Values.api).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ir-engine.api.serviceAccountName" . }}
  labels:
    {{- include "ir-engine.api.labels" . | nindent 4 }}  
  annotations:
    {{- if eq .Values.cloudProvider "gcp" }}
    iam.gke.io/gcp-service-account: gke-api-sa@{{ .Release.Namespace }}.iam.gserviceaccount.com
    {{- end }}
    {{- with .Values.api.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
