{{- if (.Values.api).enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ir-engine.api.fullname" . }}
  labels:
    {{- include "ir-engine.api.labels" . | nindent 4 }}
data:
{{- if .Values.instanceserver.extraEnv }}
  {{- range $key, $value := .Values.instanceserver.extraEnv }}
    {{- if or (kindIs "string" $value) (not (hasKey $value "valueFrom")) }}
  {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if .Values.client.extraEnv }}
  {{- range $key, $value := .Values.client.extraEnv }}
    {{- if or (kindIs "string" $value) (not (hasKey $value "valueFrom")) }}
  {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if .Values.api.extraEnv }}
  {{- range $key, $value := .Values.api.extraEnv }}
    {{- if or (kindIs "string" $value) (not (hasKey $value "valueFrom")) }}
  {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if .Values.api.config }}
  NODE_CONFIG: '{{ mustToJson .Values.api.config }}'
{{- end }}
{{- end -}}
