{{- if and (.Values.api).enabled ((.Values.api).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ir-engine.api.serviceAccountName" . }}
  labels:
    {{- include "ir-engine.api.labels" . | nindent 4 }}  
  annotations:
    iam.gke.io/gcp-service-account: gke-builder-sa@ir-engine-dev.iam.gserviceaccount.com
    {{- with .Values.api.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
