{{- if and (.Values.batchinvalidator).enabled ((.Values.batchinvalidator).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ir-engine.batchinvalidator.serviceAccountName" . }}  
  labels:
    {{- include "ir-engine.batchinvalidator.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: gke-builder-sa@ir-engine-dev.iam.gserviceaccount.com
    {{- with .Values.batchinvalidator.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}
