{{- if and (.Values.batchinvalidator).enabled ((.Values.batchinvalidator).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ir-engine.batchinvalidator.serviceAccountName" . }}  
  labels:
    {{- include "ir-engine.batchinvalidator.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.cloudProvider "gcp" }}
    iam.gke.io/gcp-service-account: mysql-user-sa@{{ .Values.googleProjectID }}.iam.gserviceaccount.com
    {{- end}}
    {{- with .Values.batchinvalidator.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}
