{{- if and (.Values.client).enabled (ne (.Values.client).serveFromApi true) (ne (((.Values.builder.extraEnv).SERVE_CLIENT_FROM_STORAGE_PROVIDER) | default "false") "true") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ir-engine.client.fullname" . }}
  labels:
    {{- include "ir-engine.client.labels" . | nindent 4 }}
data:
{{- if .Values.client.extraEnv }}
  {{- range $key, $value := .Values.client.extraEnv }}
    {{- if or (kindIs "string" $value) (not (hasKey $value "valueFrom")) }}
  {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if .Values.client.config }}
  NODE_CONFIG: '{{ mustToJson .Values.client.config }}'
{{- end }}
{{- end }}
