{{- if and (.Values.cloudflaresync).enabled ((.Values.cloudflaresync).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ir-engine.cloudflaresync.serviceAccountName" . }}  
  labels:
    {{- include "ir-engine.cloudflaresync.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.cloudProvider "gcp" }}
    iam.gke.io/gcp-service-account: ir-engine-sa@{{ .Values.googleProjectID }}.iam.gserviceaccount.com
    {{- end }}
    {{- with .Values.cloudflaresync.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}
