{{- if and (.Values.instanceserver).enabled ((.Values.instanceserver).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ir-engine.instanceserver.serviceAccountName" . }}  
  labels:
    {{- include "ir-engine.instanceserver.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.cloudProvider "gcp" }}
    iam.gke.io/gcp-service-account: gke-instanceserver-sa@{{ .Release.Namespace }}.iam.gserviceaccount.com
    {{- end}}
    {{- with .Values.instanceserver.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}
