{{- if (.Values.testbot).enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ir-engine.testbot.fullname" . }}
  labels:
    {{- include "ir-engine.testbot.labels" . | nindent 4 }}
data:
{{- if .Values.testbot.extraEnv }}
  {{- range $key, $value := .Values.testbot.extraEnv }}
    {{- if or (kindIs "string" $value) (not (hasKey $value "valueFrom")) }}
  {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
